zoom_factor = 0:0.02:0.2;
ch_list = 0.5;
nth_list = 20;
QID = 'common';
eqname = 'eq30';
casebase = ['-pickProblem 0 '...
            '-save_singleEcoli_vtk 0 '...
            '-rh1 1 '...
            '-rh2 0.09653 '...
            '-eh -0.8 '...
            '-ph 2.3938 '...
            '-hfct 1 ',... 
            '-with_cover 2 ',...
            '-left_hand 0 ',...
            '-rs1 4.324 '...
            '-rs2 4.324 '...
            '-ls 47.645 '...
            '-ds 0.8 '...
            '-es -1 '...
            '-rT1 1 ',...
            '-rT2 0.07722 ',...
            '-ntT 20 ',...
            '-eT -0.8 ',...
            '-with_T_geo 1 ',...
            '-dist_hs 0.5019 '...
            '-ksp_max_it 500 '...
            '-plot_geo 0 '...
            '-rel_wsz 0 '...
            '-rel_whz 1 '...
            '-ffweight 2 ',...
            '-forcepipe R09l20 '];
          
n_case = length(zoom_factor);
n_ch = length(ch_list);
fid_main = fopen('run.sh', 'w');
fprintf(fid_main, 't_dir=$PWD\n');
for i1 = 1:n_ch
  ch = ch_list(i1);
  nth = nth_list(i1);
  dirname = sprintf('%03d', ch*100);
  mkdir(dirname);
  cd(dirname);
  fprintf(fid_main, 'cd $t_dir/%s\n', dirname);

  fid2 = fopen('run.sh', 'w');
  for i0 = 1:n_case
    if zoom_factor(i0) - 0 < 1e-8
      t_zoom_factor = 1;
      pybase = 'mpirun -n 24 python ../../single_ecoli.py';
      sm = 'pf';
    else
      t_zoom_factor = zoom_factor(i0);
      pybase = 'mpirun -n 24 python ../../ecoliInPipe.py';
      sm = 'pf_stokesletsInPipe';
    end
    fname = sprintf('%s_%s_%04d', eqname, dirname, int16(zoom_factor(i0)*1000));
    fid = fopen([fname, '.pbs'], 'w');
    fprintf(fid, '#! /bin/bash\n');
    fprintf(fid, '#PBS -M zhangji@csrc.ac.cn\n');
    fprintf(fid, ['#PBS -N ', fname, '\n']);
    fprintf(fid, '#PBS -l nodes=1:ppn=24\n');
    fprintf(fid, '#PBS -l walltime=24:00:00\n');
    fprintf(fid, '#PBS -q %s\n', QID);
    fprintf(fid, '\n');
    fprintf(fid, 'cd $PBS_O_WORKDIR\n');
    fprintf(fid, '\n');
    fprintf(fid, '%s %s -sm %s -nth %d -ch %f -prb_index %03d -zoom_factor %f -f %s > %s.txt\n',...
      pybase, casebase, sm, nth, ch, i0, t_zoom_factor, fname, fname);
    fclose(fid);
    fprintf(fid2, ['qsub ', fname, '.pbs; \n']);
    
    fprintf(fid_main, ['qsub ', fname, '.pbs; \n']);
  end
  fclose(fid2);
  cd('../');
end
fprintf(fid_main, 'cd ../ \n');
fclose(fid_main);







